### ISSUE TITLE
Version 1.1.1 fails in firebase verify token

### ISSUE THREAD

**Issue by ildemartinez** [Aginix/nestjs-firebase-admin#210]
Using the 1.1.1 version get this issue when try to verify a user token:

 errorInfo: {
    code: 'auth/invalid-credential',
    message: 'Must initialize app with a cert credential or set your Firebase project ID as the GOOGLE_CLOUD_PROJECT environment variable to call verifyIdToken().'
  },

I do the validation this way:

    FirebaseAdminModule.forRootAsync({
      useFactory: () => ({
        credential: admin.credential.applicationDefault()
      })
    }),

and

![imagen](https://user-images.githubusercontent.com/1641352/89738256-78bf7c80-da77-11ea-9f3d-78b5bd848369.png)

downgrading to 1.0.9 solves the problem

Firebase versions
"firebase": "^7.17.2",
    "firebase-admin": "^8.13.0",
    "firebase-functions": "^3.9.0",
    "firebase-tools": "^8.7.0",

**Comment by sokolej79** [comment]
Same error after upgrade to 1.1.1.
Error:
Must initialize app with a cert credential or set your Firebase project ID as the GOOGLE_CLOUD_PROJECT environment variable to call verifyIdToken()

**Comment by n3n** [comment]
@ildemartinez @sokolej79 Could you try `v2.0.0` with `firebase-admin (v9.x.x)`

**Comment by ildemartinez** [comment]
Hello

v2.0.0 with firebase-admin 9.1.0 seems to work fine!!!

thank you a lot
