### ISSUE TITLE
error while nest build

### ISSUE THREAD

**Issue by aakashguptaa** [Aginix/nestjs-firebase-admin#259]
[91m[96mnode_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-firestore.service.d.ts[0m:[93m9[0m:[93m5[0m - [91merror[0m[90m TS2416: [0mProperty 'collectionGroup' in type 'FirebaseFirestoreService' is not assignable to the same property in base type 'Firestore'.
  Type '(collectionId: string) => Query<DocumentData>' is not assignable to type '(collectionId: string) => CollectionGroup<DocumentData>'.
    Property 'getPartitions' is missing in type 'Query<DocumentData>' but required in type 'CollectionGroup<DocumentData>'.

[7m9[0m     collectionGroup(collectionId: string): FirebaseFirestore.Query;
[7m [0m [91m    ~~~~~~~~~~~~~~~[0m

  [96mnode_modules/@google-cloud/firestore/types/firestore.d.ts[0m:[93m1552[0m:[93m5[0m
    [7m1552[0m     getPartitions(
    [7m    [0m [96m    ~~~~~~~~~~~~~[0m
    'getPartitions' is declared here.

[0mFound 1 error(s).

Able to fix this when changed from 
    collectionGroup(collectionId: string): FirebaseFirestore.Query;
to   
  collectionGroup(collectionId: string): FirebaseFirestore.CollectionGroup;
 in  node_modules\@aginix\nestjs-firebase-admin\dist\services\firebase-admin-firestore.service.d.ts

**Comment by n3n** [comment]
@aakashguptaa You can try `v2.0.2`.

**Comment by aakashguptaa** [comment]
Thanks Issue Is Resolved
