### ISSUE TITLE
gitlab build fail

### ISSUE THREAD

**Issue by aakashguptaa** [Aginix/nestjs-firebase-admin#290]
[91m[96mnode_modules/@aginix/nestjs-firebase-admin/dist/services/firebase-admin-authentication.service.d.ts[0m:[93m5[0m:[93m51[0m - [91merror[0m[90m TS2694: [0mNamespace '"/app/node_modules/firebase-admin/lib/auth/index"' has no exported member 'admin'.

[7m5[0m     get auth(): import("firebase-admin/lib/auth").admin.auth.Auth;

please look into it 
getting failed build from gitlab ci/cd

**Comment by GuilhermeCunha** [comment]
Any changes??

**Comment by Pitazzo** [comment]
I'm having the same issue

**Comment by aakashguptaa** [comment]
only workaround i did was to create build(dist) manually and removed build command in gitlab but need a fix for this asap.
There are few firebase dependencies issues that is causing build failed.

**Comment by n3n** [comment]
@aakashguptaa @Pitazzo @GuilhermeCunha  Could you try `v2.1.0`?
